name: parkeasy
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  cloud_firestore: ^4.9.2
  country_picker: ^2.0.21
  firebase_auth: ^4.10.0
  firebase_storage: ^11.2.7
  flutter:
    sdk: flutter
  
  fluttertoast: ^8.2.2
  intl: ^0.18.1
  material_design_icons_flutter: ^7.0.7296
  provider: ^6.0.5
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/Vehicle/